[package]
name = "web_service"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
shared_utils = {workspace = true}
anyhow = {workspace = true}
dotenv = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
axum = {workspace = true}
tower = {workspace = true}
tower-http = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
askama = "0.12.0"
chrono = "0.4.31"
cocoon = "0.4.1"
=======
anyhow = "1.0.72"
askama = "0.12.0"
axum = "0.6.20"
chrono = "0.4.31"
cocoon = "0.4.1"
dotenv = {workspace = true}
>>>>>>> 927e9e6 (restructure project to split up services)
futures-util = "0.3.28"
humantime = "2.1.0"
lazy_static = "1.4.0"
libsql = { git = "https://github.com/tursodatabase/libsql" }
reqwest = { version = "0.11.18", features = ["json"] }
<<<<<<< HEAD
=======
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
sha2 = "0.10.7"
tokio = {workspace = true}
# tokio-tungstenite = { version = "0.20.1", features = ["native-tls"] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["fs", "compression-gzip"] }
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
>>>>>>> 927e9e6 (restructure project to split up services)
url = "2.4.0"
webhook = "2.1.2"
