[workspace]
members = ["web_service"]
resolver = "2"

[workspace.dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio = { version = "1.31.0", features = ["full"] }
dotenv = "0.15.0"
