# https://fly.io/docs/reference/configuration/

app = "troyonthetrails"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "troyonthetrails_data"
  destination = "/data"

[env]
  HOST = "troyonthetrails.com"
  LOG_LEVEL = "debug"

[checks]
  [checks.name_of_your_http_check]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/healthcheck"
    port = 8080
    timeout = "10s"
    type = "http"
