# https://fly.io/docs/reference/configuration/

app = "troyonthetrails"
primary_region = "ord"

[processes]
  web_service = "web_service"
  map_service = "map_service"

[build]

[http_service]
  processes = ["web_service"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  HOST = "troyonthetrails.com"
  RUST_LOG = "web_service=debug,map_service=debug"
  PRIMARY_REGION = "ord"
  MAP_SERVICE_URL="http://map_service.process.troyonthetrails.internal:7070/"

[checks]
  [checks.web_health]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/healthcheck"
    port = 8080
    timeout = "10s"
    type = "http"
    processes = ["web_service"]
  [checks.map_health]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/healthcheck"
    port = 7070
    timeout = "10s"
    type = "http"
    processes = ["map_service"]
