# https://fly.io/docs/reference/configuration/

app = "troyonthetrails"
primary_region = "ord"

[processes]
  web_service = "web_service"
  map_service = "map_service"

[build]

# HTTP service for web_service
[[services]]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web_service"]

  [services.ports]
    handlers = ["http"]
    port = 8080

  [services.http_checks]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/healthcheck"
    port = 8080
    timeout = "10s"
    type = "http"

[env]
  HOST = "troyonthetrails.com"
  RUST_LOG = "web_service=debug,map_service=debug"
  PRIMARY_REGION = "ord"
