version: '3'
tasks:
  default:
    cmds:
      - task: dev
  tailwind-generate:
    cmds:
      - npx tailwindcss -i ./styles/tailwind.css -o ./assets/main.css
  build:
    cmds:
      - cargo build
  run:
    cmds:
      - task: tailwind-generate
      - cargo run
  dev:
    aliases: [watch]
    cmds:
      - cargo watch -s 'task run'
    env:
      RUST_BACKTRACE: 1
  deploy:
    cmds:
      - flyctl deploy
  stop-app:
    cmds:
      - flyctl scale count 0 -a troyonthetrails
  start-app:
    cmds:
      - flyctl scale count 1 -a troyonthetrai
