version: '3'
tasks:
  default:
    cmds:
      - task: dev
  tailwind-generate:
    dir: 'web_service'
    cmds:
      - npx tailwindcss -i ./styles/tailwind.css -o ./assets/main.css
  build:
    cmds:
      - cargo build
  run-web:
    dir: 'web_service'
    cmds:
      - task: tailwind-generate
      - cargo run
  run-map:
    dir: 'map_service'
    cmds:
      - npm run build
      - cargo run
  dev:
    aliases: [watch]
    cmds:
      - geckodriver &
      - cargo watch -s 'task run-map'
    env:
      RUST_BACKTRACE: 1
  deploy:
    cmds:
      - flyctl deploy
  stop-app:
    cmds:
      - flyctl scale count 0 -a troyonthetrails
  start-app:
    cmds:
      - flyctl scale count 1 -a troyonthetrails
