version: '3'
tasks:
  default:
    cmds:
      - task: dev
  tailwind-generate:
    dir: 'web_service'
    cmds:
      - npm run tailwind:generate
  build:
    cmds:
      - cargo build
  run-web:
    dir: 'web_service'
    cmds:
      - task: tailwind-generate
      - cargo run
  dev:
    aliases: [watch]
    cmds:
      - cargo watch -s 'task run-web'
    env:
      RUST_BACKTRACE: 1
  deploy:
    cmds:
      - flyctl deploy
  stop-app:
    cmds:
      - flyctl scale count 0 -a troyonthetrails
  start-app:
    cmds:
      - flyctl scale count 1 -a troyonthetrails
